export { Carousel } from './Carousel';
export { Sparkles, WhatsAppIcon, InstagramIcon } from './icons';
export { featuredItems, testimonials } from './data';
export { HeroSection } from './HeroSection';
export { CollectionsSection } from './CollectionsSection';
export { FeaturedSection } from './FeaturedSection';
export { TestimonialsSection } from './TestimonialsSection';
export { WhyUsSection } from './WhyUsSection';
export { AboutSection } from './AboutSection';
export { EnquirySection } from './EnquirySection';
